version: "2"

linters:
  default: none
  enable:
    - dupl
    - errcheck
    - funlen
    - gocognit
    - gocyclo
    - govet
    - nestif
    - unused
  settings:
    dupl:
      threshold: 50
    funlen:
      lines: 60
      statements: 60
      ignore-comments: true
    gocognit:
      min-complexity: 16
    gocyclo:
      min-complexity: 16
    nestif:
      min-complexity: 4

formatters:
  enable:
    - gofmt

issues:
  new-from-rev: b23bd45de1753fd6020cc08c2a49ab415dc947f7
  whole-files: false
