app:
  name: workbrench
  env: dev
  addr: ":8080"

database:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "zentao"
  dbname: "workbrench"
  charset: "utf8mb4"
  parseTime: true
  loc: "Local"

zentao:
  url: "https://customer.chandao.net/api.php/v1"
  account: "encrypt"
  password: "Asd123456"

session:
  cookieName: workbrench_session
  lifetimeHours: 2

log:
  level: debug
  dir: logs

layout:
  # 导航样式 sidebar(侧边导航) | top(顶部导航)
  nav: top
